image: python:3.10

stages:
  - build
  - test

pages:
  script:
  - pip install sphinx
  - cd docs
  - make html
  - mv build/html public
  artifacts:
    paths:
    - public

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V  # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt

build:
  stage: build
  script:
    - python setup.py install

test:
  stage: test
  script: 
    - python -m pytest
