import argparse, textwrap


def parse_arguments():
    p = argparse.ArgumentParser(
        description="Localise", 
        formatter_class=argparse.RawTextHelpFormatter
    )
    
    mode_group = p.add_mutually_exclusive_group(required=True)
    mode_group.add_argument('--train', action='store_true', 
                            help='Train the model to localise a structure.')
    mode_group.add_argument('--predict', action='store_true', 
                            help='Localise a structure with the model.')

    common_group = p.add_argument_group('Common options')
    predict_group = p.add_argument_group('Prediction mode')
    train_group = p.add_argument_group('Training mode')
    
    # shared arguments  
    common_group.add_argument(
        '--subject', '-subject', required=True, type=str, 
        help='Path to the subject directory or a txt file with subject paths.'
    )

    common_group.add_argument(
        '--seed', '-x', required=True, type=str, 
        help="Path to the binary seed mask."
    )
    
    common_group.add_argument(
        '--masks', '-i', required=True, type=str,
        help="Path to the folder that contains anatomical masks, \
            e.g. the masks folder generated by `create_masks` in previous steps."
    )
    
    common_group.add_argument(
        '--out', '-o', required=True, type=str, 
        help="Output filename for the localised structure (if in prediction mode), "
             "or the output filename for the trained model (if in training mode)."
    )
    
    common_group.add_argument(
        '--tracts', '-p', required=False, type=str,
        help="Path to the folder that contains connectivity features, \
            e.g. the tracts folder containing tract-density maps."
    )

    common_group.add_argument(
        '--hemisphere', '-c', required=False, type=str,
        help="Hemisphere of the structure to be localised. Can be left or right. \
            Will run for both hemispheres if not specified."
    )

    common_group.add_argument(
        '--tracts_list', '-l', required=False, type=str,
        help=textwrap.dedent('''\
            Txt file that contain a list of tract-density files. 
            The txt file should look like
            seeds_to_target1.nii.gz
            seeds_to_target2.nii.gz
            seeds_to_target3.nii.gz
            ...
            Only basename is needed, without the path.
        ''')
    )

    common_group.add_argument(
        '--data', '-d', required=False, type=str,
        help="Path to the presaved *.npy file of tract-density maps. \
            Must be specified if the --tracts_list option is not used."
    )

    common_group.add_argument(
        '--atlas', '-a', required=False, type=str, default='default',
        help="Path to the atlas (group-average proability map) of the structure \
            to be localised. Will use the default map if --structure is specified."
    )
    
    common_group.add_argument(
        '--spatial', action='store_true', required=False,
        help='Use conditional random field (recommended).'
    )
    
    common_group.add_argument(
        '--verbose', '-v', action='store_true', required=False, 
        help="Increase output verbosity."
    )
    
    # predict group
    predict_group.add_argument(
        '--structure', '-r', required=False, type=str,
        help="Structure to be localised in lower case, e.g., 'vim' or 'lgn'." 
             "Required if --model is not specified."
    )

    # TODO: more modalities to be implemented
    predict_group.add_argument(
        '--data_type', '-t', type=str, required=False, 
        help="Data_type (or modality). can be singleshell, diffusion, \
            resting-state, etc..."
    )
    
    predict_group.add_argument(
        '--model', '-m', required=False, type=str,
        help='Path to the pre-trained model. Required if --structure \
            is not specified.'
    )
    
    # training mode args
    train_group.add_argument(
        '--labels', '-b', required=False, type=str, 
        help="Path to the training labels of the structure (required for training). \
            Must be in the same space as the connectivity features."
    )

    train_group.add_argument(
        '--epochs', '-e', required=False, type=int, 
        default=100,
        help="Number of epochs for training. Required for the training mode."
    )

    args = p.parse_args()

    # at least one of the two should be specified
    if args.tracts is None and args.data is None:
        p.error("Please specify the connectivity features or the \
            tract-density maps for prediction when using a custom model.")
        
    # labels must be specified for training
    if args.train and args.labels is None:
        p.error('Please specify the training labels.')

    if args.train:
        # under training mode, default not using atlas
        if args.atlas == 'default':
            args.atlas = args.structure # atlas is either none or the structure
        # under training mode, either specify the target list or the presaved data

    if args.predict:
        if args.structure is None:
            # if use custom model, must specify the structure
            if args.model is None:
                p.error("Please specify a structure to be localised or a \
                    pre-trained model for prediction.")
            # if structure is not specified, can't use default atlas
            if args.atlas == 'default':
                p.error("Please specify an atlas (group-average proability map) for prediction when using a custom model.")
            if args.tracts_list is None and args.data is None:
                p.error("Please specify the list of tract-density maps when using a custom model.")
        # if using the default models, must specify the data_type
        if args.model is None and args.data_type is None:
            p.error('When using the default models, you must specify the --data_type.')

    return args