import argparse
import textwrap


def parse_arguments():
    """Parse command line arguments for the localise tool."""
    p = argparse.ArgumentParser(
        description=textwrap.dedent("""
            Localise - A tool for localising brain structures using connectivity-based features.

            This tool can train models to localise specific brain structures (like VIM, LGN) 
            using diffusion MRI tractography data, or use pre-trained models for prediction.
            It supports both training new models and making predictions on new subjects.
        """).strip(),
        formatter_class=argparse.RawTextHelpFormatter
    )
    
    # Mode selection
    mode_group = p.add_mutually_exclusive_group(required=True)
    mode_group.add_argument(
        '--train', action='store_true', 
        help='Train the model to localise a structure.'
    )
    mode_group.add_argument(
        '--predict', action='store_true', 
        help='Localise a structure with the model.'
    )

    # common arguments
    common_group = p.add_argument_group('Common options')
    predict_group = p.add_argument_group('Prediction mode')
    train_group = p.add_argument_group('Training mode')
    
    # shared arguments  
    common_group.add_argument(
        '--subject', required=True, type=str, 
        help='Path to the subject directory or a txt file with subject paths.'
    )
    
    common_group.add_argument(
        '--masks', required=True, type=str,
        help=textwrap.dedent("""
            Path to the folder that contains anatomical masks.
            For example, the masks folder generated by create_masks in previous steps.
        """).strip()
    )
    
    common_group.add_argument(
        '--seed', help="Path to the binary seed mask."
    )

    common_group.add_argument(
        '--tracts',
        help=textwrap.dedent("""
            Path to the folder that contains connectivity features.
            For example, the tracts folder containing tract-density maps.
        """).strip()
    )

    common_group.add_argument(
        '--hemisphere', choices=['left', 'right'],
        help='Hemisphere of the structure to be localised (default: both hemispheres)'
    )

    common_group.add_argument(
        '--tracts-list',
        help=textwrap.dedent("""
            Text file containing a list of tract-density files.
            The file should contain one filename per line (basename only):
            
            seeds_to_target1.nii.gz
            seeds_to_target2.nii.gz
            seeds_to_target3.nii.gz
        """).strip()
    )

    common_group.add_argument(
        '--data',
        help=textwrap.dedent("""
            Path to the presaved *.npy file of tract-density maps.
            Must be specified if --tracts_list is not used.
        """).strip()
    )

    common_group.add_argument(
        '--atlas', nargs='?', const='default', default=None,
        help=textwrap.dedent("""
            Path to the atlas (group-average probability map) of the structure.
            Will use the default map if --structure is specified.
        """).strip()
    )
    
    common_group.add_argument(
        '--spatial', action='store_true',
        help='Use conditional random field (recommended).'
    )
    
    common_group.add_argument(
        '--verbose', '-v', action='store_true', 
        help="Increase output verbosity."
    )
    
    # predict group
    predict_group.add_argument(
        '--out', 
        help=textwrap.dedent("""
            Output filename for the localised structure (if in prediction mode), 
            or the output filename for the trained model (if in training mode).
        """).strip()
    )                                                                                                                                                                     
    
    predict_group.add_argument(
        '--structure',
        help=textwrap.dedent("""
            Structure to be localised in lower case, e.g., 'vim' or 'lgn'.
            Required if --model is not specified.
        """).strip()
    )

    # TODO: more modalities to be implemented
    predict_group.add_argument(
        '--data-type',
        help=textwrap.dedent("""
            Data type (or modality). can be singleshell, diffusion, resting-state, etc...
        """).strip()
    )
    
    predict_group.add_argument(
        '--model',
        help=textwrap.dedent("""
            Path to the pre-trained model.
            Required if --structure is not specified.
        """).strip()
    )
    
    # training mode args
    train_group.add_argument(
        '--out-model',
        help=textwrap.dedent("""
            Path to save the trained model.
        """).strip()
    )

    train_group.add_argument(
        '--labels',
        help=textwrap.dedent("""
            Path to the training labels of the structure (required for training).
            Must be in the same space as the connectivity features.
        """).strip()
    )

    train_group.add_argument(
        '--epochs', type=int, default=100,
        help=textwrap.dedent("""
            Number of epochs for training (default: %(default)s).
        """).strip()
    )

    args = p.parse_args()
    _validate_args(p, args)

    return args


def _validate_args(p, args):
    """Validate argument combinations and requirements."""

    # at least one of the two should be specified
    if not args.tracts and not args.data:
        p.error("Please specify either --tracts or --data for connectivity features.")

    if args.train:
        # under training mode, default not using atlas
        if not args.labels:
            p.error('Training mode requires --labels.')
        if not args.seed:
            p.error('Training mode requires --seed.')
        if not args.out_model:
            p.error('Training mode requires --out-model.')

    if args.predict:
        if not args.out:
            p.error('Prediction mode requires --out directory')
            
        # using default models
        if not args.model:
            if not args.structure:
                p.error('Please specify either --structure or --model.')
            if not args.data_type:
                p.error('Default models require --data-type.')
                
        else:
            if not args.seed:
                p.error('Custom models require --seed.')
            if not args.tracts_list and not args.data:
                p.error('Custom models require --tracts-list or --data.')
            if args.atlas == 'default':
                p.error('Custom models require --atlas path.')

    # Set atlas to structure name if using default
    if args.atlas == 'default':
        if not args.structure:
            p.error('Specify --structure if you want to use atlas as an additional feature.')
        else:
            args.atlas = args.structure
