"""Argument definitions and validation for the train and predict subcommands."""

import textwrap

from localise.utils import is_model_path


def add_common_arguments(p):
    """Arguments shared by the train and predict subcommands."""
    p.add_argument(
        '--masks', type=str,
        help=textwrap.dedent("""
            Path to the folder that contains anatomical masks
            (or a txt file with one masks folder per subject).
            For example, the masks folder generated by prepare-masks in previous steps.
        """).strip()
    )

    p.add_argument(
        '--seed', help="Path to the binary seed mask."
    )

    p.add_argument(
        '--tracts',
        help=textwrap.dedent("""
            Path to the folder that contains connectivity features
            (or a txt file with one folder per subject).
            For example, the tracts folder containing tract-density maps.
        """).strip()
    )

    p.add_argument(
        '--hemisphere', choices=['left', 'right'],
        help='Hemisphere of the structure to be localised '
             '(prediction default: both hemispheres).'
    )

    p.add_argument(
        '--tracts-list',
        help=textwrap.dedent("""
            Text file containing a list of tract-density files.
            The file should contain one filename per line (basename only):

            seeds_to_target1.nii.gz
            seeds_to_target2.nii.gz
            seeds_to_target3.nii.gz

            If not given, a tracts_list.txt generated by prepare-tracts is
            picked up automatically from the tracts folder.
        """).strip()
    )

    p.add_argument(
        '--data',
        help=textwrap.dedent("""
            Path to the presaved *.npy file of tract-density maps.
            Must be specified if --tracts-list is not used.
        """).strip()
    )

    p.add_argument(
        '--structure',
        help=textwrap.dedent("""
            Structure to be localised in lower case, e.g., 'vim' or 'lgn'.
        """).strip()
    )

    p.add_argument(
        '--atlas', nargs='?', const='default', default=None,
        help=textwrap.dedent("""
            Path to the atlas (group-average probability map) of the structure.
            Will use the default map if --structure is specified.
        """).strip()
    )

    p.add_argument(
        '--spatial', action='store_true',
        help='Use conditional random field (recommended).'
    )

    p.add_argument(
        '--verbose', '-v', action='store_true',
        help="Increase output verbosity."
    )


def add_predict_arguments(p):
    """Arguments for the predict subcommand."""
    add_common_arguments(p)

    p.add_argument(
        '--out',
        help='Output folder for the localised structure '
             '(the probability map is saved as <out>/<hemisphere>/probmap.nii.gz).'
    )

    p.add_argument(
        '--model',
        help=textwrap.dedent("""
            The model to use: either the name of a shipped pretrained model,
            identified by the low-quality data protocol it was trained for
            (vim ships 2mm, 2mm_single32, single32; default: 2mm_single32),
            or the path to your own trained model (*.pth).
        """).strip()
    )


def add_train_arguments(p):
    """Arguments for the train subcommand."""
    add_common_arguments(p)

    p.add_argument(
        '--out-model',
        help=textwrap.dedent("""
            Path to save the trained model.
        """).strip()
    )

    p.add_argument(
        '--labels',
        help=textwrap.dedent("""
            Path to the training labels of the structure (required for training).
            Must be in the same space as the connectivity features.
        """).strip()
    )

    p.add_argument(
        '--epochs', type=int, default=100,
        help=textwrap.dedent("""
            Number of epochs for training (default: %(default)s).
        """).strip()
    )


def _resolve_default_atlas(p, args):
    """Resolve --atlas without a value to the structure's default map."""
    if args.atlas == 'default':
        if not args.structure:
            p.error('Specify --structure if you want to use atlas as an additional feature.')
        else:
            args.atlas = args.structure


def validate_predict(p, args):
    """Validate argument combinations for the predict subcommand."""
    if not args.tracts and not args.data:
        p.error("Please specify either --tracts or --data for connectivity features.")

    if not args.masks and not args.seed:
        p.error('Please specify either --masks or --seed.')

    if not args.out:
        p.error('Prediction requires --out directory')

    if is_model_path(args.model):
        # a custom trained model
        if not args.seed:
            p.error('Custom models require --seed.')
        # a tracts_list.txt generated by prepare-tracts can be picked up from
        # the tracts folder at run time
        if not args.tracts_list and not args.data and not args.tracts:
            p.error('Custom models require --tracts-list or --data.')
        if args.atlas == 'default':
            p.error('Custom models require --atlas path.')

    else:
        # a shipped pretrained model (named, or the default)
        if not args.structure:
            p.error('Please specify --structure (or provide your own trained '
                    'model via --model).')

    _resolve_default_atlas(p, args)


def validate_train(p, args):
    """Validate argument combinations for the train subcommand."""
    if not args.tracts and not args.data:
        p.error("Please specify either --tracts or --data for connectivity features.")

    if not args.labels:
        p.error('Training requires --labels.')
    if not args.seed:
        p.error('Training requires --seed.')
    if not args.out_model:
        p.error('Training requires --out-model.')

    _resolve_default_atlas(p, args)
