import os, logging
from pathlib import Path
from localise.load import load_data, load_features, ShuffledDataLoader
from localise.train import train_without_val
from localise.predict import apply_pretrained_model
from localise.utils import save_nifti, get_resources_path


RESOURCES_PATH = get_resources_path()
SEEDS_DICT = {
    'vim': 'tha',
    'lgn': 'lgn_bin',
}
# powers applied to tract densities; shared by training and prediction so that
# a model trained with this tool always matches the features built at predict time
POWER = [2, 1, 0.5]
        
def check_values(arg):
    """
    Check if the input argument is a file or a directory.
    If it is a txt file, return a list of values.
    """
    if arg is not None:
        path = Path(arg)
        if path.suffix == '.txt':
            with open(path, 'r') as f:
                return [Path(line.strip()) for line in f]
        else:
            return [path]
    else:
        return None

def return_hemisphere(hemisphere):
    """Normalise a hemisphere name to 'left' or 'right'."""
    if isinstance(hemisphere, str):
        if hemisphere.lower() in ['left', 'l']:
            return 'left'
        if hemisphere.lower() in ['right', 'r']:
            return 'right'
    raise ValueError(
        f'Invalid hemisphere: {hemisphere}. '
        'Please specify left or right.'
    )

def check_prediction_params(
    masks, seed=None, structure=None, tracts=None, 
    tracts_list=None, data=None, atlas=None, out=None, 
    model=None, data_type=None, hemisphere='left', spatial=True
):
    """
    Validate and process input parameters for tract analysis. (single subject)
    
    Returns:
    dict: A dictionary containing the validated and processed parameters.
    """
    params = locals()
    
    if seed is None:
        if masks is None:
            raise ValueError(
                'Please specify the path to the masks '
                'if you do not specify the seed.'
            )
        if structure is None:
            raise ValueError(
                'When using a custom model, '
                'please specify the seed mask.'
            )
        params['seed'] = [
            mask_path / hemisphere / f'{SEEDS_DICT[structure]}.nii.gz' 
            for mask_path in check_values(masks)
        ]
    else:
        params['seed'] = check_values(seed)

    params['masks'] = (
        [mask_path / hemisphere for mask_path in check_values(masks)] 
        if masks is not None else [None] * len(params['seed'])
    )
    # check params and return path objects
    if out is None: 
        raise ValueError('Please specify the output name.')
    params['out'] = [out_path / hemisphere / 'probmap.nii.gz' 
                     for out_path in check_values(out)]

    if atlas == 'default':
        if structure is None:
            raise ValueError(
                'When using a custom model, either set `atlas=None`, '
                'or specify your own group-average probability map.'
            )
        if masks is None:
            raise ValueError(
                'The default atlas lives inside the masks folder '
                '(masks/<hemisphere>/<structure>.nii.gz); please specify '
                'the masks folder to use it.'
            )
        params['atlas'] = [mask_path / f'{structure}.nii.gz'
                           for mask_path in params['masks']]
    elif atlas is not None:
        params['atlas'] = check_values(atlas)
    else:
        params['atlas'] = [None] * len(params['masks'])

    params['tracts'] = (
        [tract_path / hemisphere for tract_path in check_values(tracts)]
        if tracts is not None
        else [None] * len(params['masks'])
    )

    # prefer a tracts_list.txt generated by prepare-tracts next to the tract
    # maps: it records the exact feature order the maps were produced in
    # (for multiple subjects, the first subject's list is used - all subjects
    # are assumed to have been prepared with the same protocol)
    if (tracts_list is None and data is None
            and params['tracts'] and params['tracts'][0] is not None
            and (params['tracts'][0] / 'tracts_list.txt').exists()):
        params['tracts_list'] = params['tracts'][0] / 'tracts_list.txt'
        logging.info(f'Using the tract list found at {params["tracts_list"]}.')

    if data is None:
        if None in params['tracts']:
            raise ValueError(
                'Please specify path to the tract-density maps '
                'or use the presaved data.'
            )
        if params['tracts_list'] is None and structure is None:
            raise ValueError(
                'When using a custom model, '
                'you should either specify the list containing the targets, '
                'or use pre-saved data.'
            )
        params['data'] = [None] * len(params['masks'])
    else:
        params['data'] = check_values(data)

    if model is None:
        params['model'] = _handle_default_model(
            structure=structure, data_type=data_type, hemisphere=hemisphere, 
            spatial=spatial, atlas=atlas
        )
        # checking whether or not to use default target list
        if None in params['data'] and params['tracts_list'] is None:
            params['tracts_list'] = (RESOURCES_PATH / 'data' / 
                                     f'{structure}_default_target_list.txt')
            logging.info('Using default tract list.')
        # the user is using the default model but not the default target list
        else:
            # either tracts_list is none (when using presaved data) 
            # or a specified list
            logging.info('Please make sure your data or tracts_list matches ' + \
                         f'the order of the default target list.')
    else:
        logging.info(f'Using the custom model stored in {params["model"]}.')
        params['model'] = Path(params['model']).resolve()
    return params

def _handle_default_model(structure, data_type, hemisphere, spatial, atlas):
    """handle the case when a default model is used"""
    if structure is None or data_type is None:
        raise ValueError('When using the default model, you must specify '
                         'both the structure to be localised and the data_type.')

    logging.info(f'Using the default model for localising {structure} on {data_type}...')

    model_name = (
        f'{"spatial_model" if spatial else "model"}_with_prior.pth' 
        if atlas is not None 
        else f'{"spatial_model" if spatial else "model"}.pth'
    )
    model_path = (RESOURCES_PATH / 'models' / structure / data_type /
             hemisphere / model_name)

    if not model_path.exists():
        structure_dir = RESOURCES_PATH / 'models' / structure
        available = sorted(
            d.name for d in structure_dir.iterdir()
            if (d / hemisphere / model_name).exists()
        ) if structure_dir.is_dir() else []
        hint = (
            f"Available data types for {structure}: {', '.join(available)}."
            if available else
            f"No pretrained models are shipped for {structure}; "
            "train your own with `localise train` and pass it via --model."
        )
        raise ValueError(
            f"No pretrained model for structure={structure} on data_type={data_type}. {hint}"
        )

    return model_path

def predict_mode(masks, seed=None, structure=None, tracts=None,
                 tracts_list=None, data=None, atlas=None, out=None, model=None,
                 spatial=True, data_type=None, hemisphere=None, verbose=True):
    """Main function for prediction mode.

    If hemisphere is None, both hemispheres are localised (only possible with
    the standard masks/tracts folder layout; explicit seed, data, atlas, or
    model paths are hemisphere-specific, so they require an explicit
    hemisphere). Returns a list of per-subject predictions for a single
    hemisphere, or a dict {'left': [...], 'right': [...]} for both.
    """
    if verbose:
        logging.basicConfig(level=logging.INFO)

    logging.info('Predict mode on. \n')
    if hemisphere is None:
        hemisphere_specific = {
            'seed': seed, 'data': data, 'model': model,
            'atlas': None if atlas in (None, 'default') else atlas,
        }
        given = [name for name, value in hemisphere_specific.items()
                 if value is not None]
        if given:
            raise ValueError(
                'Please specify the hemisphere: '
                f'{", ".join(given)} paths are hemisphere-specific.'
            )
        hemispheres = ['left', 'right']
    else:
        hemispheres = [return_hemisphere(hemisphere)]

    predictions = {}
    for hemi in hemispheres:
        params = check_prediction_params(
            masks=masks, seed=seed, structure=structure, tracts=tracts,
            tracts_list=tracts_list, data=data, atlas=atlas, out=out, model=model,
            data_type=data_type, hemisphere=hemi, spatial=spatial
        )

        # if data is not specified, load the data from the target list
        target_list = None
        if params['tracts_list'] is not None:
            with open(params['tracts_list'], 'r') as f:
                target_list = [line.strip() for line in f if line.strip()]

        batches = [
            load_features(
                seed=params['seed'][i],
                tracts=params['tracts'][i],
                target_list=target_list,
                data=params['data'][i],
                atlas=params['atlas'][i],
                power=POWER
            )
            for i in range(len(params['seed']))
        ]

        predictions[hemi] = apply_pretrained_model(
            batches, params['model'],
            spatial=spatial
        )

        logging.info(f'Localise ({hemi}) done. Now saving results...')
        # save to nii files
        for i, prediction in enumerate(predictions[hemi]):
            out_file = Path(params['out'][i])
            out_file.parent.mkdir(parents=True, exist_ok=True)
            save_nifti(
                prediction.detach().numpy()[:, -1],
                str(params['seed'][i]), str(out_file)
            )

    logging.info('Done.')

    return predictions if len(hemispheres) > 1 else predictions[hemispheres[0]]

def check_training_params(seed, labels, masks=None, tracts=None, tracts_list=None, 
                          data=None, atlas=None, out_model=None, 
                          hemisphere='left', epochs=100):
    """Validate and process input parameters for training mode."""
    params = locals()
    params['seed'] = check_values(seed)
    params['labels'] = check_values(labels)

    if out_model is None:
        raise ValueError('Please specify the output model name.')
    params['out_model'] = Path(out_model)
    
    params['masks'] = ([mask_path / hemisphere for mask_path in check_values(masks)] 
                       if masks is not None else [None] * len(params['seed']))
    
    params['tracts'] = (
        [tract_path / hemisphere for tract_path in check_values(tracts)] 
        if tracts is not None else [None] * len(params['seed'])
    )
    
    if data is None:
        if tracts is None or tracts_list is None:
            raise ValueError(
                'Please specify path to the tract-density maps '
                'and the list of targetsor use the presaved data.'
            )
        params['data'] = [None] * len(params['seed'])
    else:
        params['data'] = check_values(data)

    params['atlas'] = ([atlas_path for atlas_path in check_values(atlas)] 
                       if atlas is not None else [None] * len(params['seed']))
    params['epochs'] = epochs
    return params

def train_mode(masks, labels, tracts=None, tracts_list=None, 
               seed=None, data=None, atlas=None, out_model=None, 
               spatial=True, hemisphere=None, epochs=100, verbose=True):
    """Main function for training mode."""
    if verbose:
        logging.basicConfig(level=logging.INFO)

    logging.info('Training mode on.\n')
    if seed is None or labels is None:
        raise ValueError('Training requires both seed and labels.')

    if hemisphere is not None:
        hemisphere = return_hemisphere(hemisphere)
    elif masks is not None or tracts is not None:
        raise ValueError(
            'Please specify the hemisphere: a model is trained per hemisphere, '
            'and the masks/tracts folders are resolved per hemisphere.'
        )

    params = check_training_params(
        masks=masks, labels=labels, tracts=tracts, tracts_list=tracts_list,
        seed=seed, data=data, atlas=atlas, out_model=out_model,
        hemisphere=hemisphere, epochs=epochs
    )

    data = load_data(
        seed=params['seed'],
        labels=params['labels'],
        tracts=params['tracts'],
        target_list=params['tracts_list'],
        data=params['data'],
        atlas=params['atlas'],
        power=POWER
    )

    params['out_model'].parent.mkdir(parents=True, exist_ok=True)
    dataloader = ShuffledDataLoader(data)
    model = train_without_val(dataloader, n_epochs=params['epochs'],
                              spatial_model=spatial,
                              model_save_path=str(params['out_model']))

    return model
