#!/bin/bash

#   Copyright (C) 2019 University of Oxford
#
#   SHCOPYRIGHT

# Written by Ying-Qiu Zheng

Usage() {
    echo ""
    echo "Usage: create_tracts -i subj001/roi -m subj001/dMRI.bedpostX -s seed.nii.gz"
    echo ""
    echo "creates tracts for the specified seed, using fiber samples estimated via BedpostX"
    echo ""
    echo ""
    echo "Compulsory arguments:"
    echo ""
    echo "-bpx <folder>                                       Path to bedpostx folder"
    echo "-inputdir <folder>                                  Path to mask folder"
    echo "-seed <path>                                        Path to seed mask."
    echo "-out <folder>                                       Path to output folder."
    echo ""
    echo ""
    echo "Optional arguments:"
    echo ""
    echo "-warp <ref2diff> <diff2ref>                         (Optional) Transformation matrix/field between the reference space (i.e., the space of the anatomical masks) and the diffusion space."
    echo "                                                               Necessary if the reference space is not the diffusion space."
    echo "-ref <path>                                         (Optional) Path to reference image, usually in the individual T1 native space."
    echo "                                                               Necessary if the reference space is not the diffusion space."
    echo "-ptx_opts <options.txt>	                            (Optional) Pass extra probtrackx2 options as a text file to override defaults, e.g. --steplength=0.2 --distthresh=10"
    echo "-brainmask <path>                                   (Optional) Path to binary brain mask in the diffusion space. Default will search for nodif_brain_mask.nii.gz under the bedpostx folder."
    echo "-gpu                                                (Optional) Use the GPU version of probtractx2."
    echo ""
    echo "For more detailed information, consult the documentation."
    exit 1
}


[ -z "$1" ] && Usage

if [ -z "$FSLDIR" ]; then
  echo "Environment variable $FSLDIR does not exist. Please set up FSLDIR. "
  exit 1
fi

get_abs_file_path() {
    file_path=$1

    # Check if realpath is available
    if command -v realpath > /dev/null 2>&1; then
        abs_path=$(realpath "$file_path")
    # Fallback to readlink -f if realpath is not available
    elif command -v readlink > /dev/null 2>&1; then
        abs_path=$(readlink -f "$file_path")
    else
        echo "Error: realpath and readlink commands are not available."
        return 1
    fi

    echo "$abs_path"
}

### some default values
prog="probtrackx2"
ptx_opts=""

### parse arguments
while [ -n "$1" ]; do
  case "$1" in
    -help)
    Usage
    ;;
    -gpu)
    prog="probtrackx2_gpu"
    ;;
    -seed)
    seed=$2
    shift
    ;;
    -ref)
    ref=$2
    shift
    ;;
    -bpx)
    bpx=$2
    shift
    ;;
    -out)
    out=$2
    shift
    ;;
    -inputdir)
    inputdir=$2
    shift
    ;;
    -brainmask)
    brainmask=$2
    shift
    ;;
    -warp)
    ref2diff=$2
    diff2ref=$3
    shift;
    shift;;
    -ptx_opts)
    ptx_opts=`cat "$2"`
    shift
    ;;
    *)
    echo "Unknown option: $1"
    exit 1
    ;;
  esac
  shift
done

### Check if required arguments are provided
if [ -z "$inputdir" ]; then
  echo "Error: Missing required argument -inputdir, the folder that contains anatomical masks."
  exit 1
elif [ ! -d $inputdir ]; then
  echo "$inputdir does not exist. Please double check the path."
  exit 1
else
  refpath=$(get_abs_file_path "$inputdir")
fi

if [ -z "$bpx" ]; then
  echo "Error: Missing required argument -bpx, the bedpostx folder. "
  exit 1
fi

if [ -z "$out" ]; then
  echo "Error: Missing required argument -out. Please specify the output folder. "
  exit 1
else
  out="$out/tracts"
  if [ ! -d $out ]; then
    mkdir -p $out
  fi
fi

if [ -z "$seed" ]; then
  echo "Error: Missing required argument -seed. Please specify the seed mask (stored under the masks folder)."
  exit 1
fi

seed=$(basename $seed)

if [ -z "$brainmask" ]; then
  brainmask=$bpx/nodif_brain_mask
  if [ ! -f $brainmask.nii.gz ] && [ ! -f $brainmask.nii ]; then
    echo "$brainmask.nii.gz or $brainmask.nii does not exist under $bpx. Creating one..."
    fslmaths $bpx/mean_fsumsamples -thr 0 -bin $brainmask
  fi
fi

if [ -f $out/../create_tracts_cmds ]; then
  rm $out/../create_tracts_cmds
fi
# for left and right hemispheres
for hemi in left right; do
  if [ ! -d $out/$hemi ]; then
    mkdir $out/$hemi
  fi
  ## create a list containing the anatomical masks
  echo $inputdir/$hemi/ar_mask{1..8}.nii.gz > $out/$hemi/targets.txt;
  echo $inputdir/$hemi/or_mask{1..10}.nii.gz >> $out/$hemi/targets.txt;
  echo $inputdir/$hemi/str_mask{1..10}.nii.gz >> $out/$hemi/targets.txt;
  echo $inputdir/$hemi/atr_mask{1..8}.nii.gz >> $out/$hemi/targets.txt;
  echo $inputdir/$hemi/fx_mask{1..10}.nii.gz >> $out/$hemi/targets.txt;
  echo $inputdir/$hemi/to_precentral_mask{1..12}.nii.gz  >> $out/$hemi/targets.txt;
  echo $inputdir/$hemi/to_postcentral_mask{1..12}.nii.gz  >> $out/$hemi/targets.txt;
  echo $inputdir/$hemi/{1..75}.nii.gz >> $out/$hemi/targets.txt;

  opts="-x $inputdir/$hemi/$seed -s $bpx/merged -m $brainmask --dir=$out/$hemi $ptx_opts"

  if [ ! -z "$ref2diff" ]; then
    opts="$opts --xfm=$ref2diff --invxfm=$diff2ref"
    if [ ! -z "$ref" ]; then
      opts="$opts --seedref=$ref"
    else
      opts="$opts --seedref=$inputdir/$hemi/$seed"
    fi
  fi

  cmd="$FSLDIR/bin/$prog $opts"
  cmd="$cmd --targetmasks=$inputdir/$hemi/targets.txt"
  cmd="$cmd --avoid=$inputdir/$hemi/cerebellum --stop=$inputdir/cortex"

  ### run tractography...
  echo $cmd >> $out/../create_tracts_cmds;
  #eval $cmd;

  echo $inputdir/$hemi/scpct_mask{1..15}.nii.gz > $out/$hemi/scpct_targets.txt;
  echo $inputdir/$hemi/cerebellum_target.nii.gz >> $out/$hemi/scpct_targets.txt;
  cmd="$FSLDIR/bin/$prog $opts"
  cmd="$cmd --targetmasks=$out/$hemi/scpct_targets.txt"
  cmd="$cmd --avoid=$out/$hemi/exclusion --stop=$out/$hemi/stop_for_scpct"
  echo $cmd >> $out/../create_tracts_cmds;
  #eval $cmd;
done

if [ ! -d $out/logs ]; then
  mkdir $out/logs
fi;

if [ "`fsl_sub --has_queues`" == "Yes" ]; then
  if $gpu; then
    fsl_sub -T 300 -R 30 -n --coprocessor=cuda  -N create_tracts -l "$out/logs" -t "$out/create_tracts_cmds"
  else
    fsl_sub -T 2160 -R 30 -n -N create_tracts -l $out/logs -t $out/create_tracts_cmds
  fi
else
  bash $out/create_tracts_cmds
fi
