#!/bin/bash

#   Copyright (C) 2019 University of Oxford
#
#   SHCOPYRIGHT

# Written by Ying-Qiu Zheng

Usage() {
    echo ""
    echo "Usage:"
    echo ""
    echo "create_tracts -bpx <bedpostX_dir> -out <output_dir> -masks <masks_dir> -str <str_name>"
    echo "create_tracts -bpx <bedpostX_dir> -out <output_dir> -masks <masks_dir> -str <str_name> -warp <ref2diff> <diff2ref> -ref <refimage> -gpu"
    echo "create_tracts -help"
    echo ""
    echo ""
    echo "Example: "
    echo ""
    echo "create_tracts -masks subj001/masks -bpx subj001/dMRI.bedpostX -seed thalamus.nii.gz -out subj001"
    echo ""
    echo ""
    echo "creates tracts for the specified seed, using fiber samples estimated via BedpostX"
    echo ""
    echo ""
    echo "Compulsory arguments:"
    echo ""
    echo "-bpx <folder>                                       Path to bedpostx folder"
    echo "-masks <folder>                                     Path to mask folder"
    echo "-str <structure_name>                               Structure to be localised, e.g., vim, lgn, etc."
    echo "-out <folder>                                       Path to output folder."
    echo ""
    echo ""
    echo "Optional arguments:"
    echo ""
    echo "-warp <ref2diff> <diff2ref>                         (Optional) Transformation matrix/field between the reference space (i.e., the space of the anatomical masks) and the diffusion space."
    echo "                                                               Necessary if the reference space is not the diffusion space."
    echo "-ref <path>                                         (Optional) Path to reference image, usually in the individual T1 native space."
    echo "                                                               Necessary if the reference space is not the diffusion space."
    echo "-ptx_opts <options.txt>	                            (Optional) Pass extra probtrackx2 options as a text file to override defaults, e.g. --steplength=0.2 --distthresh=10"
    echo "-gpu                                                (Optional) Use the GPU version of probtractx2."
    echo ""
    exit 1
}


[ -z "$1" ] && Usage

if [ -z "$FSLDIR" ]; then
  echo "Environment variable $FSLDIR does not exist. Please set up FSLDIR. "
  exit 1
fi

get_abs_file_path() {
    file_path=$1

    # Check if realpath is available
    if command -v realpath > /dev/null 2>&1; then
        abs_path=$(realpath "$file_path")
    # Fallback to readlink -f if realpath is not available
    elif command -v readlink > /dev/null 2>&1; then
        abs_path=$(readlink -f "$file_path")
    else
        echo "Error: realpath and readlink commands are not available."
        return 1
    fi

    echo "$abs_path"
}

### some default values
prog="probtrackx2"
ptx_opts=""

### parse arguments
while [ -n "$1" ]; do
  case "$1" in
    -help)
    Usage
    ;;
    -gpu)
    prog="probtrackx2_gpu"
    ;;
    -str)
    str="$2"
    shift
    ;;
    -ref)
    ref="$2"
    shift
    ;;
    -bpx)
    bpx="$2"
    shift
    ;;
    -out)
    out="$2"
    shift
    ;;
    -masks)
    inputdir="$2"
    shift
    ;;
    -str)
    str="$2"
    shift
    ;;
    -warp)
    ref2diff="$2"
    diff2ref="$3"
    shift;
    shift;;
    -ptx_opts)
    ptx_opts=`cat "$2"`
    shift
    ;;
    *)
    echo "Unknown option: $1"
    exit 1
    ;;
  esac
  shift
done

### Check if required arguments are provided
if [ -z "$inputdir" ]; then
  echo "Error: Missing required argument -masks, the folder that contains anatomical masks."
  exit 1
elif [ ! -d $inputdir ]; then
  echo "$inputdir does not exist. Please double check the path."
  exit 1
else
  refpath=$(get_abs_file_path "$inputdir")
fi

if [ -z "$bpx" ]; then
  echo "Error: Missing required argument -bpx, the bedpostx folder. "
  exit 1
fi

if [ -z "$out" ]; then
  echo "Error: Missing required argument -out. Please specify the output folder. "
  exit 1
else
  out="$out/$str/tracts"
  if [ ! -d "$out" ]; then
    mkdir -p "$out"
  fi
fi

if [ -z "$str" ]; then
  echo "Error: Missing required argument -str. Please specify the structure to be localised."
  exit 1
fi

# set the seed for tractography
if [[ $str == "vim" ]]; then
  seed="tha.nii.gz"
elif [[ $str == "lgn" ]]; then
  seed="lgn_bin.nii.gz"
fi

if [ -z "$brainmask" ]; then
  brainmask="$bpx/nodif_brain_mask"
  if [ ! -f "$brainmask.nii.gz" ] && [ ! -f "$brainmask.nii" ]; then
    echo "$brainmask.nii.gz or $brainmask.nii does not exist under $bpx. Creating one..."
    fslmaths "$bpx/mean_fsumsamples" -thr 0 -bin "$brainmask"
  fi
fi

if [ -f "$out/../create_tracts_cmds" ]; then
  rm "$out/../create_tracts_cmds"
fi
# for left and right hemispheres
for hemi in left right; do
  if [ ! -d "$out/$hemi" ]; then
    mkdir "$out/$hemi"
  fi
  ## create a list containing the anatomical masks
  echo "$inputdir/$hemi/ar_mask{1..8}.nii.gz" > "$out/$hemi/targets.txt";
  echo "$inputdir/$hemi/or_mask{1..10}.nii.gz" >> "$out/$hemi/targets.txt";
  echo "$inputdir/$hemi/str_mask{1..10}.nii.gz" >> "$out/$hemi/targets.txt";
  echo "$inputdir/$hemi/atr_mask{1..8}.nii.gz" >> "$out/$hemi/targets.txt";
  echo "$inputdir/$hemi/fx_mask{1..10}.nii.gz" >> "$out/$hemi/targets.txt";
  echo "$inputdir/$hemi/to_precentral_mask{1..12}.nii.gz"  >> "$out/$hemi/targets.txt";
  echo "$inputdir/$hemi/to_postcentral_mask{1..12}.nii.gz"  >> "$out/$hemi/targets.txt";
  echo "$inputdir/$hemi/{1..75}.nii.gz" >> "$out/$hemi/targets.txt";
  # create a list containing termination masks
  echo "$inputdir/cortex.nii.gz" > "$out/$hemi/stops.txt"
  echo "$inputdir/csf.nii.gz" >> "$out/$hemi/stops.txt"

  opts="-x $inputdir/$hemi/$seed -s $bpx/merged -m $brainmask --dir=$out/$hemi --forcedir $ptx_opts"

  if [ ! -z "$ref2diff" ]; then
    opts="$opts --xfm=$ref2diff --invxfm=$diff2ref"
    if [ ! -z "$ref" ]; then
      opts="$opts --seedref=$ref"
    else
      opts="$opts --seedref=$inputdir/$hemi/$seed"
    fi
  fi

  cmd="$FSLDIR/bin/$prog $opts"
  cmd="$cmd --targetmasks=$out/$hemi/targets.txt"
  cmd="$cmd --avoid=$inputdir/$hemi/exclusion --stop=$out/$hemi/stops.txt"

  ### run tractography...
  echo $cmd >> $out/../create_tracts_cmds;
  #eval $cmd;
  if [[ "$str" == "vim" ]]; then  
    ## extra features for VIM
    echo $inputdir/$hemi/scpct_mask{1..15}.nii.gz > $out/$hemi/scpct_targets.txt;
    echo $inputdir/$hemi/cerebellum_target.nii.gz >> $out/$hemi/scpct_targets.txt;
    cmd="$FSLDIR/bin/$prog $opts"
    cmd="$cmd --targetmasks=$out/$hemi/scpct_targets.txt"
    cmd="$cmd --avoid=$inputdir/$hemi/exclusion --stop=$inputdir/$hemi/stop_for_scpct"
    echo $cmd >> $out/../create_tracts_cmds;
  elif [[ "$str" == "lgn" ]]
    echo ""; # TODO implement additional tractography protocols for LGN
  fi
  #eval $cmd;
done

if [ ! -d "$out/../logs" ]; then
  mkdir "$out/../logs"
fi;

queue_status=`fsl_sub --has_queues`
if [[ "$queue_status" == "Yes" ]]; then
  if $gpu; then
    fsl_sub -T 300 -R 30 -n --coprocessor=cuda  -N create_tracts -l "$out/../logs" -t "$out/create_tracts_cmds"
  else
    fsl_sub -T 2160 -R 30 -n -N create_tracts -l "$out/../logs" -t "$out/../create_tracts_cmds"
  fi
else
  bash "$out/../create_tracts_cmds"
fi
